<?php return array (
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'backend\\Controllers\\auth' => 'modules/backend/controllers/auth.php',
  'backend\\Controllers\\index' => 'modules/backend/controllers/index.php',
  'cms\\Controllers\\index' => 'modules/cms/controllers/index.php',
  'system\\Controllers\\settings' => 'modules/system/controllers/settings.php',
  'cms\\Controllers\\themes' => 'modules/cms/controllers/themes.php',
  'system\\Controllers\\updates' => 'modules/system/controllers/updates.php',
  'cms\\Controllers\\themeoptions' => 'modules/cms/controllers/themeoptions.php',
  'system\\Controllers\\eventlogs' => 'modules/system/controllers/eventlogs.php',
  'backend\\Controllers\\media' => 'modules/backend/controllers/media.php',
  'martin\\forms\\Plugin' => 'plugins/martin/forms/Plugin.php',
  'Martin\\Forms\\Models\\Settings' => 'plugins/martin/forms/models/Settings.php',
  'Martin\\Forms\\Classes\\BackendHelpers' => 'plugins/martin/forms/classes/BackendHelpers.php',
  'Martin\\Forms\\Classes\\UnreadRecords' => 'plugins/martin/forms/classes/UnreadRecords.php',
  'Martin\\Forms\\Models\\Record' => 'plugins/martin/forms/models/Record.php',
  'Martin\\Forms\\Classes\\ReCaptcha' => 'plugins/martin/forms/classes/ReCaptcha.php',
  'Martin\\Forms\\Classes\\SharedProperties' => 'plugins/martin/forms/classes/SharedProperties.php',
  'Martin\\Forms\\Classes\\MagicForm' => 'plugins/martin/forms/classes/MagicForm.php',
  'Martin\\Forms\\Components\\GenericForm' => 'plugins/martin/forms/components/GenericForm.php',
  'Martin\\Forms\\Traits\\ComponentUtils' => 'plugins/martin/forms/traits/ComponentUtils.php',
  'Martin\\Forms\\Traits\\FileUploader' => 'plugins/martin/forms/traits/FileUploader.php',
  'Martin\\Forms\\Components\\UploadForm' => 'plugins/martin/forms/components/UploadForm.php',
  'Martin\\Forms\\Components\\EmptyForm' => 'plugins/martin/forms/components/EmptyForm.php',
);